name: Arcien
favicon: null
layout_spectrum: 0.00821
typography_spectrum: 0.30383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.31570319388993084
  lightness: 0.7735858459491283
  saturation: 0.620867065852508
  rhythmicContrast: 0.2794337111990899
purpose: []
