name: Arcien
favicon: null
layout_spectrum: 0.00821
typography_spectrum: 0.30383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebebeb'
    - '#fdb42e'
    - '#a7675a'
    - '#7db9ab'
    - '#161617'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
